version: '3'

services:

  zalenium:
      image: dosel/zalenium
      container_name: zalenium
      hostname: localhost
      tty: true
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /tmp/videos:/home/seluser/videos
          - /usr/local/bin/docker:/usr/local/bin/docker
      ports:
          - 4444:4444
      command: >
          start --desiredContainers 2
                --maxDockerSeleniumContainers 8
                --screenWidth 800 --screenHeight 600
                --timeZone "India"
                --videoRecordingEnabled true

  gradle:

      image: gradle
      container_name: gradle
      depends_on:
          - zalenium
      volumes:
          - .:/home/gradle

      command:
          ./wait-for-grid.sh --/bin/sh ./runGradle.sh

#      links:
#          - zalenium:localhost